apiVersion: apps/v1
kind: Deployment
metadata:
  name: buffer-deployment
  labels:
    app: buffer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: buffer
  template:
    metadata:
      labels:
        app: buffer
    spec:
      priorityClassName: buffering-priority
      containers:
        - name: pause
          image: google/pause
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "500m"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: buffering-priority
value: 0
